spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/limit_db
    username: postgres
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080