version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: limit_db
    environment:
      POSTGRES_DB: limit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - limit-network

volumes:
  pgdata:

networks:
  limit-network:
    driver: bridge